<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Academy.Agent.Audio\Academy.Agent.Audio.csproj" />
    <ProjectReference Include="..\Academy.Agent.Capture\Academy.Agent.Capture.csproj" />
  </ItemGroup>

</Project>